fixtures:
  forge_modules:
    apache: "puppetlabs/apache"
    concat: "puppetlabs/concat"
    stdlib: "puppetlabs/stdlib"
    pnp4nagios: "abstractit/pnp4nagios"
    apt: "puppetlabs/apt"
  symlinks:
    icinga: "#{source_dir}"
